export const fonts = [
  {
    id: "font_roboto_bold",
    family: "Roboto",
    fullName: "Roboto Bold",
    postScriptName: "Roboto-Bold",
    preview: "https://ik.imagekit.io/lh/fonts/v2/5zQgS86djScKA0ri67BBCqW7.png",
    style: "bold",
    url: "https://fonts.gstatic.com/s/roboto/v51/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWuYjammT.ttf",
  },
  {
    id: "font_roboto_regular",
    family: "Roboto",
    fullName: "Roboto Regular",
    postScriptName: "Roboto-Regular",
    preview: "https://ik.imagekit.io/lh/fonts/v2/5zQgS86djScKA0ri67BBCqW7.png",
    style: "regular",
    url: "https://fonts.gstatic.com/s/roboto/v51/KFOMCnqEu92Fr1ME7kSn66aGLdTylUAMQXC89YmC2DPNWubEbWmT.ttf",
  },
  {
    id: "font_outfit_bold",
    family: "Outfit",
    fullName: "Outfit Bold",
    postScriptName: "Outfit-Bold",
    preview: "https://ik.imagekit.io/lh/fonts/v2/5zQgS86djScKA0ri67BBCqW7.png",
    style: "bold",
    url: "https://fonts.gstatic.com/s/outfit/v15/QGYyz_MVcBeNP4NjuGObqx1XmO1I4deyC4E.ttf",
  },
  {
    id: "font_outfit_regular",
    family: "Outfit",
    fullName: "Outfit Regular",
    postScriptName: "Outfit-Regular",
    preview: "https://ik.imagekit.io/lh/fonts/v2/5zQgS86djScKA0ri67BBCqW7.png",
    style: "regular",
    url: "https://fonts.gstatic.com/s/outfit/v15/QGYyz_MVcBeNP4NjuGObqx1XmO1I4TC1C4E.ttf",
  },
  {
    id: "font_bangers_regular",
    family: "Bangers",
    fullName: "Bangers Regular",
    postScriptName: "Bangers-Regular",
    preview: "https://ik.imagekit.io/lh/fonts/v2/5zQgS86djScKA0ri67BBCqW7.png",
    style: "regular",
    url: "https://fonts.gstatic.com/s/bangers/v25/FeVQS0BTqb0h60ACL5k.ttf",
  },
];
