export const fonts = [
  {
    id: "font_roboto_bold",
    family: "Roboto",
    fullName: "Roboto Bold",
    postScriptName: "Roboto-Bold",
    preview: "https://ik.imagekit.io/lh/fonts/v2/5zQgS86djScKA0ri67BBCqW7.png",
    style: "bold",
    url: "https://fonts.gstatic.com/s/roboto/v29/KFOlCnqEu92Fr1MmWUlvAx05IsDqlA.ttf",
  },
  {
    id: "font_roboto_regular",
    family: "Roboto",
    fullName: "Roboto Regular",
    postScriptName: "Roboto-Regular",
    preview: "https://ik.imagekit.io/lh/fonts/v2/5zQgS86djScKA0ri67BBCqW7.png",
    style: "regular",
    url: "https://fonts.gstatic.com/s/roboto/v29/KFOmCnqEu92Fr1Mu4mxM.ttf",
  },
  {
    id: "font_outfit_bold",
    family: "Outfit",
    fullName: "Outfit Bold",
    postScriptName: "Outfit-Bold",
    preview: "https://ik.imagekit.io/lh/fonts/v2/5zQgS86djScKA0ri67BBCqW7.png",
    style: "bold",
    url: "https://fonts.gstatic.com/s/outfit/v11/QGYyz_MVcBeNP4NJtEtq.ttf",
  },
  {
    id: "font_outfit_regular",
    family: "Outfit",
    fullName: "Outfit Regular",
    postScriptName: "Outfit-Regular",
    preview: "https://ik.imagekit.io/lh/fonts/v2/5zQgS86djScKA0ri67BBCqW7.png",
    style: "regular",
    url: "https://fonts.gstatic.com/s/outfit/v11/QGYyz_MVcBeNP4NJtEtq.ttf",
  },
  {
    id: "font_bangers_regular",
    family: "Bangers",
    fullName: "Bangers Regular",
    postScriptName: "Bangers-Regular",
    preview: "https://ik.imagekit.io/lh/fonts/v2/5zQgS86djScKA0ri67BBCqW7.png",
    style: "regular",
    url: "https://fonts.gstatic.com/s/bangers/v20/FeVQS0BTqACV6KdPB9y5.ttf",
  },
];
